### ISSUE TITLE
My Checklist

### ISSUE THREAD

**Issue by dsychin** [dsychin/lfcs#1]
## 1. Essential Commands - 25%

- [x] a. [Log into local & remote graphical and text mode consoles](1-essential-commands/a.md)
- [ ] b. [Search for files (find & locate)](1-essential-commands/b.md)
- [ ] c. [Evaluate and compare the basic file system features and options](1-essential-commands/c.md)
- [ ] d. [Compare and manipulate file content (diff)](1-essential-commands/d.md)
- [x] e. [Use input-output redirection (e.g. >, >>, |, 2>)](1-essential-commands/e.md)
- [ ] f. [Analyze text using basic regular expressions (grep, sed, awk)](1-essential-commands/f.md)
- [ ] g. [Archive, backup, compress, unpack, and uncompress files (tar, gzip, bzip2, xz, rsync)](1-essential-commands/g.md)
- [x] h. [Create, delete, copy, and move files and directories](1-essential-commands/h.md)
- [ ] i. [Create and manage hard and soft links (ln)](1-essential-commands/i.md)
- [ ] l. [List, set, and change standard file permissions (including SUID/SGID, sticky bit)](1-essential-commands/l.md)
- [ ] m. [Read, and use system documentation (man, info, help)](1-essential-commands/m.md)
- [ ] n. [Manage access to the root account](1-essential-commands/n.md)

## 2. Operation of Running Systems - 20%

- [ ] a. [Boot, reboot, and shut down a system safely](2-operation-of-running-systems/a.md)
- [ ] b. [Boot or change system into different operating modes](2-operation-of-running-systems/b.md)
- [ ] c. [Install, configure and troubleshoot bootloaders](2-operation-of-running-systems/c.md)
- [ ] d. [Diagnose and manage processes](2-operation-of-running-systems/d.md)
- [ ] e. [Locate and analyze system log files](2-operation-of-running-systems/e.md)
- [ ] f. [Schedule tasks to run at a set date and time (cron, anacron, at)](2-operation-of-running-systems/f.md)
- [ ] g. [Verify completion of scheduled jobs](2-operation-of-running-systems/g.md)
- [ ] h. [Update software to provide required functionality and security](2-operation-of-running-systems/h.md)
- [ ] i. [Verify the integrity and availability of resources](2-operation-of-running-systems/i.md)
- [ ] l. [Verify the integrity and availability of key processes](2-operation-of-running-systems/l.md)
- [ ] m. [Change kernel runtime parameters, persistent and non-persistent](2-operation-of-running-systems/m.md)
- [ ] n. [Use scripting to automate system maintenance tasks](2-operation-of-running-systems/n.md)
- [ ] o. [Manage the startup process and services](2-operation-of-running-systems/o.md)
- [ ] p. [List and identify SELinux/AppArmor file and process contexts](2-operation-of-running-systems/p.md)
- [ ] q. [Manage software](2-operation-of-running-systems/q.md)
- [ ] r. [Identify the component of a Linux distribution that a file belongs to](2-operation-of-running-systems/r.md)

## 3. User and Group Management - 10%

- [ ] a. [Create, delete, and modify local user accounts](3-user-and-group-management/a.md)
- [ ] b. [Create, delete, and modify local groups and group memberships](3-user-and-group-management/b.md)
- [ ] c. [Manage system-wide environment profiles](3-user-and-group-management/c.md)
- [ ] d. [Manage template user environment (/etc/skel/)](3-user-and-group-management/d.md)
- [ ] e. [Configure user resource limits](3-user-and-group-management/e.md)
- [ ] f. [Manage user privileges](3-user-and-group-management/f.md)
- [ ] g. [Configure PAM](3-user-and-group-management/g.md)

## 4. Networking - 12%

- [ ] a. [Configure networking and hostname resolution statically or dynamically](4-networking/a.md)
- [ ] b. [Configure network services to start automatically at boot](4-networking/b.md)
- [ ] c. [Implement packet filtering (iptables, firewalld or ufw)](4-networking/c.md)
- [ ] d. [Start, stop, and check the status of network services](4-networking/d.md)
- [ ] e. [Statically route IP traffic](4-networking/e.md)
- [ ] f. [Synchronize time using other network peers](4-networking/f.md)

## 5. Service Configuration - 20%

- [ ] a. [Configure a caching DNS server](5-service-configuration/a.md)
- [ ] b. [Maintain a DNS zone](5-service-configuration/b.md)
- [ ] c. [Configure email aliases](5-service-configuration/c.md)
- [ ] d. [Configure SSH servers and clients](5-service-configuration/d.md)
- [ ] e. [Restrict access to the HTTP proxy server](5-service-configuration/e.md)
- [ ] f. [Configure an IMAP and IMAPS service](5-service-configuration/f.md)
- [ ] g. [Query and modify the behavior of system services at various operating modes](5-service-configuration/g.md)
- [ ] h. [Configure an HTTP server](5-service-configuration/h.md)
- [ ] i. [Configure HTTP server log files](5-service-configuration/i.md)
- [ ] l. [Configure a database server](5-service-configuration/l.md)
- [ ] m. [Restrict access to a web page](5-service-configuration/m.md)
- [ ] n. [Manage and configure containers](5-service-configuration/n.md)
- [ ] o. [Manage and configure Virtual Machines](5-service-configuration/o.md)

## 6. Storage Management - 13%

- [ ] a. [List, create, delete, and modify physical storage partitions (fdisk, gdisk)](6-storage-management/a.md)
- [ ] b. [Manage and configure LVM storage](6-storage-management/b.md)
- [ ] c. [Create and configure encrypted storage (LUKS)](6-storage-management/c.md)
- [ ] d. [Configure systems to mount file systems at or during boot](6-storage-management/d.md)
- [ ] e. [Configure and manage swap space](6-storage-management/e.md)
- [ ] f. [Create and manage RAID devices (mdadm)](6-storage-management/f.md)
- [ ] g. [Configure systems to mount file systems on demand](6-storage-management/g.md)
- [ ] h. [Create, manage and diagnose advanced file system permissions (lsattr, chattr, getfacl, setfacl)](6-storage-management/h.md)
- [ ] i. [Setup user and group disk quotas for filesystems](6-storage-management/i.md)
- [ ] l. [Create and configure file systems](6-storage-management/l.md)

## 7. Bonus/Miscellanea - 0%

- [ ] a. [bash](7-bonus-miscellanea/a.md)
- [x] b. [git](7-bonus-miscellanea/b.md)
- [x] c. vi(m)
- [ ] d. [Repair the GRUB from live CD or USB stick](7-bonus-miscellanea/d.md)
- [ ] e. [Install a CA certificate](7-bonus-miscellanea/e.md)
- [ ] f. [Create a self-signed SSL certificate for Apache web server](7-bonus-miscellanea/f.md)
- [ ] g. [Debugging TLS handshake issues](7-bonus-miscellanea/g.md)
- [ ] h. Chroot jails
- [ ] i. Disable ssh-login as root via PAM
- [ ] l. GNU Autotools
- [ ] m. Manage your dotfiles with GNU stow
- [ ] n. [DNS essentials](7-bonus-miscellanea/n.md)
- [ ] o. [Network-Manager](7-bonus-miscellanea/o.md)
- [ ] p. [SSH-tunneling](7-bonus-miscellanea/p.md)
- [ ] q. Troubleshooting networks
- [x] r. tmux
- [ ] s. Alpine e-mail setup
- [ ] t. How to fix Nvidia graphics card problems
- [ ] u. GPG & SSH keys
- [ ] v. How to use Linux's built-in USB attack protection
- [ ] z. [Tips & tricks](7-bonus-miscellanea/z.md)
- [ ] j. Repair a usb drive: https://www.maketecheasier.com/repair-corrupted-usb-drive-linux/
